### ISSUE TITLE
Problems on PISC

### ISSUE THREAD

**Issue by vampirely** [Li-Wanhua/GR2N#3]
Hello, the accuracy of the results I obtained by running on the PISC data set is only about 60%. I set the training parameters by installing the parameters in the article. May I ask which corresponding parameters need to be set in the PISC test to reproduce the results.

**Comment by Li-Wanhua** [comment]
Hi, thanks for the interest.
PISC dataset has two settings: Coarse relationships and Fine relationships. So which one are you referring to?
But something to notice includes 1) the metric is mAP NOT accuracy for the PISC dataset. 2) we adopted the reweighting strategy for fine-grained relationship recognition on the PISC dataset.  3) The config file for  fine-grained relationship recognition on the PISC dataset is listed as below:

`CUDA_VISIBLE_DEVICES=1,2,3 python SR_train.py --batch-size=32 \
--test-batch-size=16 --max-person=8 --image-size=448 \
--max-epochs=10 --lr=0.00001 --fc-lr=0.00001 \
--save-model='./Domain_Model/' \
--loss-weight-path='./relation_split/loss_weight.npy' \
--images-root='/home/disk0/Social_relation/PISC/image/' \
--train-file-pre='./relation_split/relation_train' \
--test-file-pre='./relation_split/relation_test' \
--num-workers=2  --num-classes=6 --time-steps=1 \
--manualSeed=768`

Hope this can help you.

**Comment by Li-Wanhua** [comment]
I think it's best to use English. If you find it inconvenient to communicate in English, you can contact me in Chinese by email.
My email is li-wh17@mails.tsinghua.edu.cn
